---

plugins: [flowtype]

env:
  node: true
  es6: true

parser: babel-eslint

parserOptions:
  ecmaVersion: 2017
  sourceType: module

rules:
  no-console: off
  no-await-in-loop: off
  no-confusing-arrow: off
  import/prefer-default-export: off

extends:
  - 'airbnb-base'
  - plugin:import/errors
  - plugin:import/warnings
